name: hyperscanai_mobile
description: "Hyperscan Mobile Application"

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <4.0.0"

dependencies:
  camera: ^0.11.1
  camera_android: ^0.10.10+1
  flutter:
    sdk: flutter
  flutter_pdfview: ^1.4.0
  google_mlkit_barcode_scanning: 0.12.1
  google_mlkit_commons: 0.8.1
  google_mlkit_digital_ink_recognition: 0.12.1
  google_mlkit_document_scanner: 0.2.1
  google_mlkit_entity_extraction: 0.13.1
  google_mlkit_face_detection: 0.11.1
  google_mlkit_image_labeling: 0.12.1
  google_mlkit_language_id: 0.11.1
  google_mlkit_object_detection: 0.13.1
  image_picker: ^1.1.2
  path: ^1.9.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/ml/
    - assets/images/
